# Downloading and Installing nginx  
- name: Download and unarchive nginx
  unarchive:
   src: http://nginx.org/download/nginx-1.10.3.tar.gz
   dest: /opt
   copy: no
   
- name: Installing nginx
  shell: ./configure --prefix=/usr && make && make install
  args:
   chdir: /opt/nginx-1.10.3
   
- name: install nginx startup script in Redhat/ubuntu
  template: src=nginx.service dest=/etc/systemd/system/nginx.service owner=root group=root mode=0755
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'Ubuntu'

- name : install nginx startup script in AmazonLinuz
  copy : src=nginx dest=/etc/sysconfig/nginx owner=root group=root mode=0755
  when: ansible_distribution == 'Amazon'
  
- name: install nginx startup script in AmazonLinuz
  template: src=nginx.init dest=/etc/init.d/nginx owner=root group=root mode=0755
  when: ansible_distribution == 'Amazon'
  
- name: start nginx and ensure started on boot
  command: nginx 