---
- name: Include amazon.yml if the operating system is redhat
  include: redhat.yml
  when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
  
- name: Include amazon.yml if the operating system is Ubuntu
  include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"