---

#install docker if not present 
- name: install docker 
  shell: curl -fsSL https://get.docker.com | sh


#copy file docker.service
- name: copy files 
  template:
    src: docker.service
    dest: /lib/systemd/system/
    mode: 0755
  when: secure

#copy file docker         
- name: copy files 
  template:
    src: docker
    dest: /etc/default/
    mode: 0755
  when: secure

#restart docker
- service:
    name: docker
    state: restarted


 