# creating a direcory for java installation in the machine
- name: creating a director for java installation
  file:
    path: /usr/lib/jvm
    state: directory
    
#download tar file
- name: download java tar file
  get_url:
    url: "https://storage.googleapis.com/jdkbucket/java.tar.gz"
    dest: /opt
    mode: 0777

#untar
- name: untar the java tar ball
  shell: tar xvzf /opt/java.tar.gz -C /opt/
    

# setting the java home path in .bashrc file
- name: setting java home path
  lineinfile:
    dest: /etc/environment
    line: JAVA_HOME=/opt/jdk1.8.0_60
    state: present

# setting the java bin path in .bashrc file
- name: setting the java path
  lineinfile:
    dest: /etc/environment
    line: PATH=$JAVA_HOME/bin:$PATH
    state: present  

# executing the source command to load functions into current shell  
# - name: running the source command
#   shell: source /etc/environment
#   args:
#     executable: /bin/bash

# - name: setting java home path
#   shell: echo JAVA_HOME is $JAVA_HOME
#   environment:
#     JAVA_HOME: /usr/lib/jvm/jdk1.8.0_60
 
# - name: export java home
#   raw: export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_60

# - name: export java PATH
#   raw: export PATH=$JAVA_HOME/bin:$PATH