---
# Downloads the Source file form server
- name: extract archive
  get_url:
    url:  http://downloads.mariadb.com/MariaDB/mariadb-10.1.22/yum/rhel/mariadb-10.1.22-rhel-7-x86_64-rpms.tar
    dest: /opt/

- name: untar
  unarchive:
    src: /opt/mariadb-10.1.22-rhel-7-x86_64-rpms.tar
    dest: /opt/
    copy: no

# Installs the rpm key to repo  
- rpm_key:
    state: present
    key: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB 
    
# Runs the shell command for the repository installed  
- name: shell command for mariadb debs
  shell: /opt/mariadb-10.1.22-rhel-7-x86_64-rpms/setup_repository
  
# Installs the mariadb-server from the Downloaded repository  
- name: install mariadb through yum repo
  yum: name=MariaDB-server 
  
# Starts the MariaDb-Serivice
- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes
  


