---
# This playbook will install mysql and create db user and give permissions.


- name: Configure host name
  command: hostname -f
  
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes



 
- name: install mysql-server
  apt: name=mysql-server state=present
  
 

- name: install mysql-server
  apt: name=mysql-server state=present

  
- name: Create Application DB User
  user: name=root password=root  state=present
