---
#this is playbook will install docker
- name: install docker
  shell: curl -fsSL https://get.docker.com | sh

- name: add user to docker group
  shell: usermod -aG docker ec2-user

- name: start docker
  service: 
    name: docker
    state: started

#copy file docker.service
- name: copy files 
  template:
    src: rhel.docker
    dest: /lib/systemd/system/docker.service
    mode: 0755
    
#copy file docker.socket
- name: copy files 
  template:
    src: docker.socket
    dest: /lib/systemd/system/docker.socket
    mode: 0755
    
#copy file docker         
- name: copy files 
  template:
    src: docker
    dest: /etc/default/
    mode: 0755

#copy scriptfile  
- name: copy scriptfile
  template:
    src: createkey.sh
    dest: /etc/
    mode: 0755
  when: secure
    
#run scriptfile
- name: run script file
  command: /etc/createkey.sh 
  when: secure

#restart docker
- service:
    name: docker
    state: restarted


